In [1]:
import pandas as pd
import geopandas as gpd

In [10]:
gold_velib = pd.read_parquet("../gold/capacity_velib_quartier.parquet")
gold_trafic = pd.read_parquet("../gold/trafic_quartiers.parquet")
gold_ratp = pd.read_parquet("../gold/nb_arrets_lignes_quartiers.parquet")
gold_stationnement = pd.read_parquet("../gold/nb_places_stationnement_quartiers.parquet")

In [20]:
gold_ratp["c_qu"] = pd.to_numeric(gold_ratp["c_qu"])
gold_trafic["c_qu"] = pd.to_numeric(gold_trafic["c_qu"])
gold_velib["c_qu"] = pd.to_numeric(gold_velib["c_qu"])
gold_stationnement["c_qu"] = pd.to_numeric(gold_stationnement["c_qu"])

In [35]:
tc_modes = (
    gold_ratp.pivot_table(
        index=["c_qu", "l_qu"],
        columns="mode",
        values="nb_lignes",
        aggfunc="sum",
        fill_value=0
    )
    .reset_index()
)

In [36]:
tc_modes

mode,c_qu,l_qu,Bus,Funicular,LocalTrain,Metro,RapidTransit,Tramway,regionalRail
0,1,Saint-Germain-l'Auxerrois,23,0,0,2,0,0,0
1,2,Halles,11,0,0,3,3,0,0
2,3,Palais-Royal,10,0,0,3,0,0,0
3,4,Place-Vendôme,5,0,0,2,0,0,0
4,5,Gaillon,11,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...
75,76,Combat,8,0,0,3,0,0,0
76,77,Belleville,6,0,0,2,0,0,0
77,78,Saint-Fargeau,21,0,0,2,0,1,0
78,79,Père-Lachaise,13,0,0,3,0,0,0
79,80,Charonne,16,0,0,3,0,1,0

In [37]:
gold_mobilite = gold_velib.merge(
    gold_stationnement,
    on=["c_qu", "l_qu"],
    how="outer"
).merge(
    gold_trafic,
    on=["c_qu", "l_qu"],
    how="outer"
).merge(
    tc_modes,
    on=["c_qu", "l_qu"],
    how="outer"
)

In [38]:
gold_mobilite

,l_qu,c_qu,velib_station,capacity,nb_places_ouvrage,nb_places_auto,stationnement_total,surface,places_km2,trafic_total_q,...,nb_arcs,occupation_moyenne_k,trafic_moyen_q,Bus,Funicular,LocalTrain,Metro,RapidTransit,Tramway,regionalRail
0,Saint-Germain-l'Auxerrois,1,3,67,944.0,104,1048.0,8.690007e+05,1205.982967,8.890007e+07,...,2080,10.215018,253.710243,23,0,0,2,0,0,0
1,Halles,2,14,378,1043.0,180,1223.0,4.124585e+05,2965.146823,3.068596e+07,...,608,9.670024,291.913651,11,0,0,3,3,0,0
2,Palais-Royal,3,6,212,562.0,171,733.0,2.736968e+05,2678.146102,9.653600e+06,...,548,3.227270,100.182648,10,0,0,3,0,0,0
3,Place-Vendôme,4,4,118,475.0,151,626.0,2.694568e+05,2323.192605,1.350918e+07,...,333,9.505632,257.023992,5,0,0,2,0,0,0
4,Gaillon,5,4,129,0.0,196,196.0,1.880122e+05,1042.485519,2.729744e+07,...,508,7.739741,311.614623,11,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Combat,76,14,367,147.0,1629,1776.0,1.294988e+06,1371.441394,2.052528e+07,...,1348,9.100330,86.780327,8,0,0,3,0,0,0
76,Belleville,77,9,319,0.0,954,954.0,8.065686e+05,1182.788353,3.280591e+07,...,1507,5.665258,138.702498,6,0,0,2,0,0,0
77,Saint-Fargeau,78,16,407,0.0,1491,1491.0,1.486971e+06,1002.709223,1.366123e+08,...,3389,7.622475,226.014657,21,0,0,2,0,1,0
78,Père-Lachaise,79,15,411,0.0,1785,1785.0,1.599002e+06,1116.321324,4.019421e+07,...,2103,7.193982,120.746858,13,0,0,3,0,0,0
79,Charonne,80,29,793,0.0,2681,2681.0,2.090904e+06,1282.220528,2.904154e+08,...,4379,7.051809,376.732249,16,0,0,3,0,1,0

In [39]:
gold_mobilite["nb_arrets"] = gold_mobilite["Bus"] + gold_mobilite["Funicular"] + gold_mobilite["LocalTrain"] + gold_mobilite["Metro"]+ gold_mobilite["Tramway"] +gold_mobilite["regionalRail"]

In [40]:
def min_max_normalize(series):
    min_val = series.min()
    max_val = series.max()

    if max_val == min_val:
        return pd.Series([100] * len(series), index=series.index)

    return 100 * (series - min_val) / (max_val - min_val)

#normalisation

In [41]:
gold_mobilite["velib_station_norm"] = min_max_normalize(gold_mobilite["velib_station"])
gold_mobilite["capacity_norm"] = min_max_normalize(gold_mobilite["capacity"])

gold_mobilite["places_km2_norm"] = min_max_normalize(gold_mobilite["places_km2"])

gold_mobilite["nb_arrets_norm"] = min_max_normalize(gold_mobilite["nb_arrets"])

gold_mobilite["trafic_moyen_norm"] = min_max_normalize(gold_mobilite["trafic_moyen_q"])
gold_mobilite["occupation_norm"] = min_max_normalize(gold_mobilite["occupation_moyenne_k"])

In [42]:
gold_mobilite["score_velib"] = (
    0.5 * gold_mobilite["velib_station_norm"] +
    0.5 * gold_mobilite["capacity_norm"]
)

gold_mobilite["score_stationnement"] = gold_mobilite["places_km2_norm"]

gold_mobilite["score_tc"] = (
    0.5 * gold_mobilite["nb_arrets_norm"] + 0
    #0.5 * gold_mobilite["nb_lignes_norm"]
)

gold_mobilite["score_trafic"] = (
    0.5 * gold_mobilite["trafic_moyen_norm"] +
    0.5 * gold_mobilite["occupation_norm"]
)

gold_mobilite["score_trafic_inverse"] = 100 - gold_mobilite["score_trafic"]

In [43]:
gold_mobilite["score_mobilite"] = (
    0.25 * gold_mobilite["score_tc"] +
    0.25 * gold_mobilite["score_velib"] +
    0.25 * gold_mobilite["score_stationnement"] +
    0.25 * gold_mobilite["score_trafic_inverse"]
)

In [46]:
gold_mobilite.head()

,l_qu,c_qu,velib_station,capacity,nb_places_ouvrage,nb_places_auto,stationnement_total,surface,places_km2,trafic_total_q,...,places_km2_norm,nb_arrets_norm,trafic_moyen_norm,occupation_norm,score_velib,score_stationnement,score_tc,score_trafic,score_trafic_inverse,score_mobilite
0,Saint-Germain-l'Auxerrois,1,3,67,944.0,104,1048.0,869000.664564,1205.982967,88900069.00,...,20.544209,51.351351,25.746006,50.334943,0.000000,20.544209,25.675676,38.040475,61.959525,27.044853
1,Halles,2,14,378,1043.0,180,1223.0,412458.496330,2965.146823,30685963.00,...,53.957446,21.621622,30.507751,46.775736,31.455696,53.957446,10.810811,38.641744,61.358256,39.395552
2,Palais-Royal,3,6,212,562.0,171,733.0,273696.793301,2678.146102,9653600.00,...,48.506207,18.918919,6.610038,4.699876,11.118143,48.506207,9.459459,5.654957,94.345043,40.857213
3,Place-Vendôme,4,4,118,475.0,151,626.0,269456.780599,2323.192605,13509181.00,...,41.764285,2.702703,26.159038,45.702141,3.818565,41.764285,1.351351,35.930590,64.069410,27.750903
4,Gaillon,5,4,129,0.0,196,196.0,188012.203850,1042.485519,27297440.95,...,17.438769,21.621622,32.963317,34.169584,4.282700,17.438769,10.810811,33.566451,66.433549,24.741457

In [47]:
gold_mobilite["score_mobilite"].max()

np.float64(60.93297946953328)

In [50]:
from pymongo import MongoClient

uri = "mongodb+srv://admin:admin@urbanexplorer.6oxlveb.mongodb.net/"
client = MongoClient(uri)

db = client["urban_db"]
db.create_collection("areas")
db.create_collection("area_profiles")
db.create_collection("area_indicators")

Collection(Database(MongoClient(host=['ac-i4voenr-shard-00-02.6oxlveb.mongodb.net:27017', 'ac-i4voenr-shard-00-01.6oxlveb.mongodb.net:27017', 'ac-i4voenr-shard-00-00.6oxlveb.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', replicaset='atlas-ncdhml-shard-0', tls=True), 'urban_db'), 'area_indicators')

In [51]:
db.areas.create_index([("area_id", 1), ("level", 1)], unique=True)
db.areas.create_index([("geometry", "2dsphere")])

db.area_profiles.create_index([("area_id", 1), ("level", 1)], unique=True)
db.area_profiles.create_index([("geometry", "2dsphere")])
db.area_profiles.create_index([("scores.score_mobilite", -1)])
db.area_profiles.create_index([("scores.score_velib", -1)])
db.area_profiles.create_index([("scores.score_tc", -1)])
db.area_profiles.create_index([("scores.score_stationnement", -1)])
db.area_profiles.create_index([("scores.score_trafic", -1)])

db.area_indicators.create_index(
    [("area_id", 1), ("level", 1), ("indicator_name", 1), ("version", 1)],
    unique=True
)
db.area_indicators.create_index([("indicator_name", 1), ("value", -1)])

'indicator_name_1_value_-1'

In [58]:
final_gdf.dtypes

n_sq_qu                      str
c_qu                       int64
c_quinsee                    str
l_qu                         str
c_ar                       int32
n_sq_ar                      str
perimetre                float64
surface_x                float64
geom_x_y                  object
st_area_shape            float64
st_perimeter_shape       float64
geometry                geometry
velib_station              int64
capacity                   int32
nb_places_ouvrage        float64
nb_places_auto             int32
stationnement_total      float64
surface_y                float64
places_km2               float64
trafic_total_q           float64
nb_mesures                 int64
nb_arcs                    int64
occupation_moyenne_k     float64
trafic_moyen_q           float64
Bus                        int64
Funicular                  int64
LocalTrain                 int64
Metro                      int64
RapidTransit               int64
Tramway                    int64
regionalRail               int64
nb_arrets                  int64
velib_station_norm       float64
capacity_norm            float64
places_km2_norm          float64
nb_arrets_norm           float64
trafic_moyen_norm        float64
occupation_norm          float64
score_velib              float64
score_stationnement      float64
score_tc                 float64
score_trafic             float64
score_trafic_inverse     float64
score_mobilite           float64
dtype: object

In [52]:
quartiers = gpd.read_file("../raw/quartier_paris.geojson")

docs = []
for _, row in quartiers.iterrows():
    doc = {
        "area_id": int(row["c_qu"]),
        "area_name": row["l_qu"],
        "level": "quartier",
        "geometry": row["geometry"].__geo_interface__,
        "properties": {
            "surface_m2": float(row["surface"]) if "surface" in row and row["surface"] is not None else None,
            "surface_km2": float(row["surface"]) / 1_000_000 if "surface" in row and row["surface"] is not None else None
        }
    }
    docs.append(doc)

if docs:
    db.areas.delete_many({})
    db.areas.insert_many(docs)

print("Areas insérés :", db.areas.count_documents({}))

Areas insérés : 80

In [59]:
from datetime import datetime, timezone
quartiers["c_qu"]=pd.to_numeric(quartiers["c_qu"])
final_gdf = quartiers.merge(gold_mobilite, on=["c_qu", "l_qu"], how="left")

docs = []
for _, row in final_gdf.iterrows():
    doc = {
        "area_id": int(row["c_qu"]),
        "area_name": row["l_qu"],
        "level": "quartier",
        "geometry": row["geometry"].__geo_interface__,
        "properties": {
            "surface_m2": float(row["surface_x"]) if pd.notna(row.get("surface_x")) else None,
            "surface_km2": float(row["surface_x"]) / 1_000_000 if pd.notna(row.get("surface_x")) else None
        },
        "metrics": {
            "velib_station": row.get("velib_station"),
            "capacity": row.get("capacity"),
            "nb_places_ouvrage": row.get("nb_places_ouvrage"),
            "nb_places_auto": row.get("nb_places_auto"),
            "stationnement_total": row.get("stationnement_total"),
            "places_km2": row.get("places_km2"),
            "trafic_total_q": row.get("trafic_total_q"),
            "nb_mesures": row.get("nb_mesures"),
            "nb_arcs": row.get("nb_arcs"),
            "occupation_moyenne_k": row.get("occupation_moyenne_k"),
            "trafic_moyen_q": row.get("trafic_moyen_q"),
            "nb_arrets": row.get("nb_arrets"),
        },
        "scores": {
            "score_velib": row.get("score_velib"),
            "score_stationnement": row.get("score_stationnement"),
            "score_trafic": row.get("score_trafic"),
            "score_trafic_inverse": row.get("score_trafic_inverse"),
            "score_tc": row.get("score_tc"),
            "score_mobilite": row.get("score_mobilite")
        },
        "updated_at": datetime.now(timezone.utc)
    }
    docs.append(doc)

if docs:
    db.area_profiles.delete_many({})
    db.area_profiles.insert_many(docs)

print("Profiles insérés :", db.area_profiles.count_documents({}))

Profiles insérés : 80