In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
parkings = gpd.read_file("../raw/stationnement-en-ouvrage.geojson")
voie_publique = gpd.read_file("../raw/stationnement-voie-publique-emplacements.geojson")
quartiers_gdf = gpd.read_file("../raw/quartier_paris.geojson")

Skipping field plage_hor1_debut: unsupported OGR type: 10
Skipping field plage_hor1_fin: unsupported OGR type: 10
Skipping field plage_hor2_debut: unsupported OGR type: 10
Skipping field plage_hor2_fin: unsupported OGR type: 10
Skipping field plage_hor3_debut: unsupported OGR type: 10
Skipping field plage_hor3_fin: unsupported OGR type: 10
c:\Users\dimit\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyogrio\raw.py:200: RuntimeWarning: Several features with id = 2383 have been found. Altering it to be unique. This warning will not be emitted anymore for this layer
  return ogr_read(

In [3]:
parkings.head()

,id,nom,insee,adresse,url,type_usagers,gratuit,nb_places,nb_pr,nb_pmr,...,parc_relai,ab_1m_rela,tf_res_1me,pass_2rm,pass_2rm_1h,pass_2rm_1m,pass_2rm_3m,pass_2rm_1a,geo_point_2d,geometry
0,75108-P-002,MALESHERBES ANJOU,75108,"20 ter boulevard malesherbes, 75008, Paris",https://www.sags-parking.fr/parking/67/paris-m...,tous,0,846.0,0,12,...,NON,NaN,206.5000,OUI,1.2,90.0,256.0,990.0,"{'lon': 2.321701826579308, 'lat': 48.872509658...",POINT (2.3217 48.87251)
1,75101-P-008,LES HALLES ST EUSTACHE,75101,"22 rue des halles, 75001, Paris",https://www.saemes.fr/fr/parking/parking-les-h...,tous,0,253.0,0,6,...,NON,NaN,NaN,OUI,1.2,90.0,256.0,990.0,"{'lon': 2.3459639824912317, 'lat': 48.86068215...",POINT (2.34596 48.86068)
2,75115-P-021,MAIRIE DU 15 EME LECOURBE,75115,"147 rue lecourbe, 75015, Paris",https://www.saemes.fr/fr/parking/parking-mairi...,tous,0,189.0,0,6,...,NON,NaN,NaN,OUI,0.8,70.0,199.0,770.0,"{'lon': 2.2995674310918996, 'lat': 48.84162433...",POINT (2.29957 48.84162)
3,75118-P-073,DAMREMONT,75118,"73 ter rue damremont, 75018, Paris",https://www.sags-parking.fr/parking/164/paris-...,abonnés,0,46.0,0,3,...,NON,NaN,151.7544,OUI,NaN,70.0,199.0,770.0,"{'lon': 2.3357544919147903, 'lat': 48.89288959...",POINT (2.33575 48.89289)
4,75108-P-014,SAINT AUGUSTIN,75108,"18 rue de laborde, 75008, Paris",https://www.saemes.fr/fr/parking/parking-st-au...,tous,0,777.0,0,10,...,NON,NaN,NaN,OUI,1.2,90.0,256.0,990.0,"{'lon': 2.320321350264016, 'lat': 48.875749605...",POINT (2.32032 48.87575)

In [4]:
quartiers_gdf = quartiers_gdf.to_crs(voie_publique.crs)
parkings = parkings.to_crs(quartiers_gdf.crs)
parkings_quartiers = gpd.sjoin(
    parkings,
    quartiers_gdf,
    how="inner",
    predicate="within"
)

In [ ]:
parkings_quartiers = parkings_quartiers[["l_qu","c_qu","id","nom","geometry","nb_places"]]

In [6]:
parkings_quartiers.head()

,l_qu,c_qu,id,nom,geometry,nb_places
0,Madeleine,31,75108-P-002,MALESHERBES ANJOU,POINT (2.3217 48.87251),846.0
1,Halles,2,75101-P-008,LES HALLES ST EUSTACHE,POINT (2.34596 48.86068),253.0
2,Saint-Lambert,57,75115-P-021,MAIRIE DU 15 EME LECOURBE,POINT (2.29957 48.84162),189.0
3,Grandes-Carrières,69,75118-P-073,DAMREMONT,POINT (2.33575 48.89289),46.0
4,Europe,32,75108-P-014,SAINT AUGUSTIN,POINT (2.32032 48.87575),777.0

In [7]:
parkings_quartiers.to_parquet("../silver/silver_parkings_quartiers.parquet")

In [8]:
voie_publique.head()

,regpri,regpar,typsta,arrond,placal,plarel,zoneres,locsta,numvoie,typevoie,...,numiris,zoneasp,stv,prefet,mtlast_edit_date_field,datereleve,n_voieadd,n_voieadf,geo_point_2d,geometry
0,PAYANT MIXTE,Mixte,Longitudinal,15,1,1,15J,Chaussée,NaN,RUE D',...,NaN,15Z7,STV Sud-Ouest,None,2020-08-25,2020-08-04,65.0,99,"{'lon': 2.308330644980031, 'lat': 48.836369292...",POINT (2.30833 48.83637)
1,2 ROUES,Vélos,Bataille,19,3,3,19H,Trottoir,7.0,AV,...,NaN,19Z4,STV Nord-Est,None,2020-09-01,2020-08-21,14.0,38,"{'lon': 2.371927146542117, 'lat': 48.883145482...",POINT (2.37193 48.88315)
2,LIVRAISON,ZL périodique,Longitudinal,16,1,1,16G,Chaussée,49.0,RUE,...,NaN,16Z2,STV Sud-Ouest,None,2019-01-04,2020-08-31,41.0,53,"{'lon': 2.294887986214173, 'lat': 48.871342928...",POINT (2.29489 48.87134)
3,PAYANT MIXTE,Mixte,Longitudinal,18,9,9,18T,Chaussée,NaN,RUE DU,...,NaN,18Z4,STV Nord-Ouest,None,2019-01-04,2020-08-31,0.0,0,"{'lon': 2.346775983852076, 'lat': 48.901359322...",POINT (2.34678 48.90136)
4,2 ROUES,Vélos,Bataille,4,20,20,4E,Trottoir,8.0,RUE,...,NaN,04Z2,STV Centre,None,2023-10-16,2023-07-16,2.0,14,"{'lon': 2.353826298705972, 'lat': 48.860071761...",POINT (2.35383 48.86007)

In [9]:
voie_publique_quartiers = gpd.sjoin(
    voie_publique,
    quartiers_gdf,
    how="inner",
    predicate="within"
)

In [10]:
voie_publique_quartiers.columns

Index(['regpri', 'regpar', 'typsta', 'arrond', 'placal', 'plarel', 'zoneres',
       'locsta', 'numvoie', 'typevoie', 'nomvoie', 'compnumvoie', 'locnum',
       'parite', 'lon', 'lar', 'surface_calculee', 'signhor', 'signvert',
       'confsign', 'typemob', 'nummob', 'id', 'id_old', 'c_voie_vp', 'n_sq_tv',
       'numilot', 'numiris', 'zoneasp', 'stv', 'prefet',
       'mtlast_edit_date_field', 'datereleve', 'n_voieadd', 'n_voieadf',
       'geo_point_2d', 'geometry', 'index_right', 'n_sq_qu', 'c_qu',
       'c_quinsee', 'l_qu', 'c_ar', 'n_sq_ar', 'perimetre', 'surface',
       'geom_x_y', 'st_area_shape', 'st_perimeter_shape'],
      dtype='str')

In [11]:
voie_publique_quartiers = voie_publique_quartiers[["l_qu","c_qu","geometry","regpri","plarel","id_old"]]

In [12]:
voie_publique_quartiers.head()

,l_qu,c_qu,geometry,regpri,plarel,id_old
0,Saint-Lambert,57,POINT (2.30833 48.83637),PAYANT MIXTE,1,021209G200509050208
1,Villette,73,POINT (2.37193 48.88315),2 ROUES,3,490302D20070123140147
2,Chaillot,64,POINT (2.29489 48.87134),LIVRAISON,1,298603G20131218114718
3,Clignancourt,70,POINT (2.34678 48.90136),PAYANT MIXTE,9,784602D20111128093613
4,Saint-Merri,13,POINT (2.35383 48.86007),2 ROUES,20,898401D20140318142817

In [13]:
voie_publique_quartiers.to_parquet("../silver/silver_voie_publique_quartiers.parquet")

In [14]:
df_parkings = pd.read_parquet("../silver/silver_parkings_quartiers.parquet")
df_voie_publique = pd.read_parquet("../silver/silver_voie_publique_quartiers.parquet")

In [15]:
categories_stationnement = [
    "PAYANT MIXTE",
    "PAYANT ROTATIF",
    "GRATUIT",
    "GIG/GIC",
    "ELECTRIQUE"
]

In [16]:
parking_auto = df_voie_publique[
    df_voie_publique["regpri"].isin(categories_stationnement)
].copy()

parking_auto["plarel"] = pd.to_numeric(
    parking_auto["plarel"], errors="coerce"
).fillna(0)

stationnement_auto_quartier = (
    parking_auto.groupby(["c_qu", "l_qu"], as_index=False)
    .agg(nb_places_auto=("plarel", "sum"))
)

print(stationnement_auto_quartier.head())

  c_qu                       l_qu  nb_places_auto
0    1  Saint-Germain-l'Auxerrois             104
1   10             Enfants-Rouges             226
2   11                   Archives             197
3   12               Sainte-Avoie              75
4   13                Saint-Merri              40

In [17]:
df_parkings["nb_places"] = pd.to_numeric(
    df_parkings["nb_places"], errors="coerce"
).fillna(0)

parking_ouvrage_quartier = (
    df_parkings.groupby(["c_qu", "l_qu"], as_index=False)
    .agg(nb_places_ouvrage=("nb_places", "sum"))
)

stationnement_quartier = parking_ouvrage_quartier.merge(
    stationnement_auto_quartier,
    on=["c_qu", "l_qu"],
    how="outer"
).fillna(0)

stationnement_quartier["stationnement_total"] = (
    stationnement_quartier["nb_places_ouvrage"] +
    stationnement_quartier["nb_places_auto"]
)

print(stationnement_quartier.head())

  c_qu                       l_qu  nb_places_ouvrage  nb_places_auto  \
0    1  Saint-Germain-l'Auxerrois              944.0             104
1   10             Enfants-Rouges                0.0             226
2   11                   Archives                0.0             197
3   12               Sainte-Avoie                0.0              75
4   13                Saint-Merri              626.0              40

   stationnement_total
0               1048.0
1                226.0
2                197.0
3                 75.0
4                666.0

In [22]:
quartiers_gdf["c_qu"] = pd.to_numeric(quartiers_gdf["c_qu"])

In [25]:
stationnement_quartier["c_qu"] = pd.to_numeric(stationnement_quartier["c_qu"])

In [31]:
stationnement_quartier = stationnement_quartier.merge(
    quartiers_gdf[["c_qu","surface"]],
    on="c_qu",
    how="left"
)

In [32]:
stationnement_quartier["places_km2"] = (
    stationnement_quartier["stationnement_total"]/
    (stationnement_quartier["surface"]/1000000)
)

In [33]:
stationnement_quartier

,c_qu,l_qu,nb_places_ouvrage,nb_places_auto,stationnement_total,surface,places_km2
0,1,Saint-Germain-l'Auxerrois,944.0,104,1048.0,8.690007e+05,1205.982967
1,10,Enfants-Rouges,0.0,226,226.0,2.717503e+05,831.645743
2,11,Archives,0.0,197,197.0,3.677284e+05,535.721492
3,12,Sainte-Avoie,0.0,75,75.0,2.133164e+05,351.590487
4,13,Saint-Merri,626.0,40,666.0,3.130404e+05,2127.520944
...,...,...,...,...,...,...,...
75,78,Saint-Fargeau,0.0,1491,1491.0,1.486971e+06,1002.709223
76,79,Père-Lachaise,0.0,1785,1785.0,1.599002e+06,1116.321324
77,8,Bonne-Nouvelle,0.0,35,35.0,2.814482e+05,124.356806
78,80,Charonne,0.0,2681,2681.0,2.090904e+06,1282.220528
79,9,Arts-et-Métiers,454.0,312,766.0,3.180877e+05,2408.140593

In [34]:
stationnement_quartier.to_parquet("../gold/nb_places_stationnement_quartiers.parquet")