In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
parkings = gpd.read_file("../raw/stationnement-en-ouvrage.geojson")
voie_publique = gpd.read_file("../raw/stationnement-voie-publique-emplacements.geojson")
iris_gdf = gpd.read_file("../raw/iris_raw_20260427.geojson")

Skipping field plage_hor1_debut: unsupported OGR type: 10
Skipping field plage_hor1_fin: unsupported OGR type: 10
Skipping field plage_hor2_debut: unsupported OGR type: 10
Skipping field plage_hor2_fin: unsupported OGR type: 10
Skipping field plage_hor3_debut: unsupported OGR type: 10
Skipping field plage_hor3_fin: unsupported OGR type: 10
c:\Users\dimit\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyogrio\raw.py:200: RuntimeWarning: Several features with id = 2383 have been found. Altering it to be unique. This warning will not be emitted anymore for this layer
  return ogr_read(

In [3]:
parkings.head()

,id,nom,insee,adresse,url,type_usagers,gratuit,nb_places,nb_pr,nb_pmr,...,parc_relai,ab_1m_rela,tf_res_1me,pass_2rm,pass_2rm_1h,pass_2rm_1m,pass_2rm_3m,pass_2rm_1a,geo_point_2d,geometry
0,75108-P-002,MALESHERBES ANJOU,75108,"20 ter boulevard malesherbes, 75008, Paris",https://www.sags-parking.fr/parking/67/paris-m...,tous,0,846.0,0,12,...,NON,NaN,206.5000,OUI,1.2,90.0,256.0,990.0,"{'lon': 2.321701826579308, 'lat': 48.872509658...",POINT (2.3217 48.87251)
1,75101-P-008,LES HALLES ST EUSTACHE,75101,"22 rue des halles, 75001, Paris",https://www.saemes.fr/fr/parking/parking-les-h...,tous,0,253.0,0,6,...,NON,NaN,NaN,OUI,1.2,90.0,256.0,990.0,"{'lon': 2.3459639824912317, 'lat': 48.86068215...",POINT (2.34596 48.86068)
2,75115-P-021,MAIRIE DU 15 EME LECOURBE,75115,"147 rue lecourbe, 75015, Paris",https://www.saemes.fr/fr/parking/parking-mairi...,tous,0,189.0,0,6,...,NON,NaN,NaN,OUI,0.8,70.0,199.0,770.0,"{'lon': 2.2995674310918996, 'lat': 48.84162433...",POINT (2.29957 48.84162)
3,75118-P-073,DAMREMONT,75118,"73 ter rue damremont, 75018, Paris",https://www.sags-parking.fr/parking/164/paris-...,abonnés,0,46.0,0,3,...,NON,NaN,151.7544,OUI,NaN,70.0,199.0,770.0,"{'lon': 2.3357544919147903, 'lat': 48.89288959...",POINT (2.33575 48.89289)
4,75108-P-014,SAINT AUGUSTIN,75108,"18 rue de laborde, 75008, Paris",https://www.saemes.fr/fr/parking/parking-st-au...,tous,0,777.0,0,10,...,NON,NaN,NaN,OUI,1.2,90.0,256.0,990.0,"{'lon': 2.320321350264016, 'lat': 48.875749605...",POINT (2.32032 48.87575)

In [5]:
iris_gdf = iris_gdf.to_crs(voie_publique.crs)
parkings = parkings.to_crs(iris_gdf.crs)
parkings_iris = gpd.sjoin(
    parkings,
    iris_gdf,
    how="inner",
    predicate="within"
)

In [9]:
parkings_iris = parkings_iris[["code_iris","nom_iris","id_left","nom","geometry","nb_places"]]

In [10]:
parkings_iris.head()

,code_iris,nom_iris,id_left,nom,geometry,nb_places
0,751083106,Madeleine 6,75108-P-002,MALESHERBES ANJOU,POINT (2.3217 48.87251),846.0
1,751010203,Les Halles 3,75101-P-008,LES HALLES ST EUSTACHE,POINT (2.34596 48.86068),253.0
2,751155729,Saint-Lambert 29,75115-P-021,MAIRIE DU 15 EME LECOURBE,POINT (2.29957 48.84162),189.0
3,751186917,Grandes Carrières 17,75118-P-073,DAMREMONT,POINT (2.33575 48.89289),46.0
4,751083201,Europe 1,75108-P-014,SAINT AUGUSTIN,POINT (2.32032 48.87575),777.0

In [11]:
parkings_iris.to_parquet("../silver/silver_parkings_iris.parquet")

In [12]:
voie_publique.head()

,regpri,regpar,typsta,arrond,placal,plarel,zoneres,locsta,numvoie,typevoie,...,numiris,zoneasp,stv,prefet,mtlast_edit_date_field,datereleve,n_voieadd,n_voieadf,geo_point_2d,geometry
0,PAYANT MIXTE,Mixte,Longitudinal,15,1,1,15J,Chaussée,NaN,RUE D',...,NaN,15Z7,STV Sud-Ouest,None,2020-08-25,2020-08-04,65.0,99,"{'lon': 2.308330644980031, 'lat': 48.836369292...",POINT (2.30833 48.83637)
1,2 ROUES,Vélos,Bataille,19,3,3,19H,Trottoir,7.0,AV,...,NaN,19Z4,STV Nord-Est,None,2020-09-01,2020-08-21,14.0,38,"{'lon': 2.371927146542117, 'lat': 48.883145482...",POINT (2.37193 48.88315)
2,LIVRAISON,ZL périodique,Longitudinal,16,1,1,16G,Chaussée,49.0,RUE,...,NaN,16Z2,STV Sud-Ouest,None,2019-01-04,2020-08-31,41.0,53,"{'lon': 2.294887986214173, 'lat': 48.871342928...",POINT (2.29489 48.87134)
3,PAYANT MIXTE,Mixte,Longitudinal,18,9,9,18T,Chaussée,NaN,RUE DU,...,NaN,18Z4,STV Nord-Ouest,None,2019-01-04,2020-08-31,0.0,0,"{'lon': 2.346775983852076, 'lat': 48.901359322...",POINT (2.34678 48.90136)
4,2 ROUES,Vélos,Bataille,4,20,20,4E,Trottoir,8.0,RUE,...,NaN,04Z2,STV Centre,None,2023-10-16,2023-07-16,2.0,14,"{'lon': 2.353826298705972, 'lat': 48.860071761...",POINT (2.35383 48.86007)

In [13]:
voie_publique_iris = gpd.sjoin(
    voie_publique,
    iris_gdf,
    how="inner",
    predicate="within"
)

In [14]:
voie_publique_iris.columns

Index(['regpri', 'regpar', 'typsta', 'arrond', 'placal', 'plarel', 'zoneres',
       'locsta', 'numvoie', 'typevoie', 'nomvoie', 'compnumvoie', 'locnum',
       'parite', 'lon', 'lar', 'surface_calculee', 'signhor', 'signvert',
       'confsign', 'typemob', 'nummob', 'id_left', 'id_old', 'c_voie_vp',
       'n_sq_tv', 'numilot', 'numiris', 'zoneasp', 'stv', 'prefet',
       'mtlast_edit_date_field', 'datereleve', 'n_voieadd', 'n_voieadf',
       'geo_point_2d_left', 'geometry', 'index_right', 'dep', 'insee_com',
       'nom_com', 'iris', 'code_iris', 'nom_iris', 'typ_iris',
       'geo_point_2d_right', 'id_right'],
      dtype='str')

In [15]:
voie_publique_iris = voie_publique_iris[["code_iris","nom_iris","geometry","regpri","plarel","id_old"]]

In [16]:
voie_publique_iris.head()

,code_iris,nom_iris,geometry,regpri,plarel,id_old
0,751155721,Saint-Lambert 21,POINT (2.30833 48.83637),PAYANT MIXTE,1,021209G200509050208
1,751197302,Villette 2,POINT (2.37193 48.88315),2 ROUES,3,490302D20070123140147
2,751166412,Chaillot 12,POINT (2.29489 48.87134),LIVRAISON,1,298603G20131218114718
3,751187027,Clignancourt 27,POINT (2.34678 48.90136),PAYANT MIXTE,9,784602D20111128093613
4,751041302,Saint-Merri 2,POINT (2.35383 48.86007),2 ROUES,20,898401D20140318142817

In [17]:
voie_publique_iris.to_parquet("../silver/silver_voie_publique_iris.parquet")

In [18]:
df_parkings = pd.read_parquet("../silver/silver_parkings_iris.parquet")
df_voie_publique = pd.read_parquet("../silver/silver_voie_publique_iris.parquet")

In [19]:
categories_stationnement = [
    "PAYANT MIXTE",
    "PAYANT ROTATIF",
    "GRATUIT",
    "GIG/GIC",
    "ELECTRIQUE"
]

In [21]:
parking_auto = df_voie_publique[
    df_voie_publique["regpri"].isin(categories_stationnement)
].copy()

parking_auto["plarel"] = pd.to_numeric(
    parking_auto["plarel"], errors="coerce"
).fillna(0)

stationnement_auto_iris = (
    parking_auto.groupby(["code_iris", "nom_iris"], as_index=False)
    .agg(nb_places_auto=("plarel", "sum"))
)

print(stationnement_auto_iris.head())

   code_iris                     nom_iris  nb_places_auto
0  751010101  Saint-Germain l'Auxerrois 1              64
1  751010102  Saint-Germain l'Auxerrois 2              24
2  751010103  Saint-Germain l'Auxerrois 3              16
3  751010202                 Les Halles 2              49
4  751010203                 Les Halles 3              46

In [23]:
df_parkings["nb_places"] = pd.to_numeric(
    df_parkings["nb_places"], errors="coerce"
).fillna(0)

parking_ouvrage_iris = (
    df_parkings.groupby(["code_iris", "nom_iris"], as_index=False)
    .agg(nb_places_ouvrage=("nb_places", "sum"))
)

stationnement_quartier = parking_ouvrage_iris.merge(
    stationnement_auto_iris,
    on=["code_iris", "nom_iris"],
    how="outer"
).fillna(0)

stationnement_quartier["stationnement_total"] = (
    stationnement_quartier["nb_places_ouvrage"] +
    stationnement_quartier["nb_places_auto"]
)

print(stationnement_quartier.head())

   code_iris                     nom_iris  nb_places_ouvrage  nb_places_auto  \
0  751010101  Saint-Germain l'Auxerrois 1                0.0            64.0
1  751010102  Saint-Germain l'Auxerrois 2              391.0            24.0
2  751010103  Saint-Germain l'Auxerrois 3              553.0            16.0
3  751010201                 Les Halles 1              462.0             0.0
4  751010202                 Les Halles 2                0.0            49.0

   stationnement_total
0                 64.0
1                415.0
2                569.0
3                462.0
4                 49.0

In [24]:
iris_gdf["code_iris"] = pd.to_numeric(iris_gdf["code_iris"])

In [25]:
stationnement_quartier["code_iris"] = pd.to_numeric(stationnement_quartier["code_iris"])

In [30]:
iris_gdf = iris_gdf.to_crs("EPSG:2154")
iris_gdf["surface"] = iris_gdf.geometry.area

In [31]:
stationnement_quartier = stationnement_quartier.merge(
    iris_gdf[["code_iris","surface"]],
    on="code_iris",
    how="left"
)

In [32]:
stationnement_quartier["places_km2"] = (
    stationnement_quartier["stationnement_total"]/
    (stationnement_quartier["surface"]/1000000)
)

In [33]:
stationnement_quartier

,code_iris,nom_iris,nb_places_ouvrage,nb_places_auto,stationnement_total,surface,places_km2
0,751010101,Saint-Germain l'Auxerrois 1,0.0,64.0,64.0,63640.345000,1005.651368
1,751010102,Saint-Germain l'Auxerrois 2,391.0,24.0,415.0,61415.305000,6757.273289
2,751010103,Saint-Germain l'Auxerrois 3,553.0,16.0,569.0,47777.310000,11909.418927
3,751010201,Les Halles 1,462.0,0.0,462.0,78283.935000,5901.593986
4,751010202,Les Halles 2,0.0,49.0,49.0,69988.105000,700.118970
...,...,...,...,...,...,...,...
968,940370104,Plateau 1,0.0,24.0,24.0,196155.005001,122.352218
969,940410202,Petit Ivry Nord,0.0,1.0,1.0,124511.495000,8.031387
970,940410203,Petit Ivry Sud,0.0,17.0,17.0,359307.420000,47.313245
971,940410301,Ivry Port Nord,0.0,12.0,12.0,777019.830002,15.443621
972,940800101,Centre Nord 1,583.0,2.0,585.0,113195.905000,5168.031476

In [ ]:
stationnement_quartier.to_parquet("../gold/nb_places_stationnement_iris.parquet")